# Generated by Django 3.0.3 on 2020-02-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input_TourDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(blank=True, max_length=200, null=True)),
                ('points_link', models.CharField(blank=True, max_length=200, null=True)),
                ('map_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fridaysocialmodel',
            name='best',
        ),
        migrations.RemoveField(
            model_name='fridaysocialmodel',
            name='honorable',
        ),
        migrations.RemoveField(
            model_name='fridaysocialmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='racingmodel',
            name='fifth',
        ),
        migrations.RemoveField(
            model_name='racingmodel',
            name='first',
        ),
        migrations.RemoveField(
            model_name='racingmodel',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='racingmodel',
            name='second',
        ),
        migrations.RemoveField(
            model_name='racingmodel',
            name='sixth',
        ),
        migrations.RemoveField(
            model_name='racingmodel',
            name='third',
        ),
        migrations.RemoveField(
            model_name='saturdaysocialmodel',
            name='best',
        ),
        migrations.RemoveField(
            model_name='saturdaysocialmodel',
            name='honorable',
        ),
        migrations.RemoveField(
            model_name='saturdaysocialmodel',
            name='name',
        ),
        migrations.DeleteModel(
            name='testmodel',
        ),
        migrations.RemoveField(
            model_name='topgolfmodel',
            name='fifth',
        ),
        migrations.RemoveField(
            model_name='topgolfmodel',
            name='first',
        ),
        migrations.RemoveField(
            model_name='topgolfmodel',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='topgolfmodel',
            name='second',
        ),
        migrations.RemoveField(
            model_name='topgolfmodel',
            name='sixth',
        ),
        migrations.RemoveField(
            model_name='topgolfmodel',
            name='third',
        ),
        migrations.DeleteModel(
            name='TourAgendaModel',
        ),
        migrations.DeleteModel(
            name='FridaySocialModel',
        ),
        migrations.DeleteModel(
            name='RacingModel',
        ),
        migrations.DeleteModel(
            name='SaturdaySocialModel',
        ),
        migrations.DeleteModel(
            name='TopGolfModel',
        ),
    ]
