# Generated by Django 3.0.3 on 2020-02-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200217_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHoleDetails',
            fields=[
                ('roundNum', models.IntegerField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(blank=True, max_length=100, null=True)),
                ('tussleName', models.CharField(blank=True, max_length=100, null=True)),
                ('scorecardLink', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
